name: Update Meme in README

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  update-meme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use the personal access token

      - name: Fetch Meme
        run: |
          curl -s https://meme-api.com/gimme/programmingmemes | jq -r '.url' > meme_url.txt
          wget -O meme.jpg $(cat meme_url.txt)

      - name: Commit and Push Meme
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the secret token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add meme.jpg
          git commit -m "Updated meme"
          git push origin main
